# Generated by Django 4.0 on 2022-01-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(default='Default Producer', max_length=255),
        ),
    ]
