# Generated by Django 4.0 on 2022-01-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
